apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
        version: v1
    spec:
      containers:
      - name: simple-api
        image: denyspolitiuk/simple-api:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
